name: Test

on:
  push:
    branches: ["main", "ci-pipeline"]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up and cache Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20.5'
          cache-dependency-path: |
            data-listener/go.sum

      - name: Install dependencies
        run: |
          cd data-listener
          go mod tidy
          go mod download 

      - name: Run tests
        run: |
          cd data-listener
          go test -v ./...

